accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


from accounts.views import RegisterView, ProfileView, ChangeProfileView, ChangePasswordView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name="registration"),
    path('<int:pk>/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/change/', ChangeProfileView.as_view(), name="change_profile"),
    path('change/password/', ChangePasswordView.as_view(), name="change_password"),

]

exam8/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import IndexView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView

# from webapp.views import IndexView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView, CartAddView, \
#     CartView, CartDeleteView, CartDeleteOneView, OrderCreate
from webapp.views.reviews import CreateReviewView, UpdateReview, DeleteReview

app_name = "webapp"

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('products/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    # path('product/<int:pk>/add-to-cart/', CartAddView.as_view(), name='add_to_cart'),
    # path('cart/', CartView.as_view(), name='cart'),
    # path('cart/<int:pk>/delete/', CartDeleteView.as_view(), name='remove_for_cart'),
    # path('cart/<int:pk>/one-delete/', CartDeleteOneView.as_view(), name='remove_one_for_cart'),
    # path('order/create/', OrderCreate.as_view(), name='order_create')
    path('product/<int:pk>/review/add/', CreateReviewView.as_view(), name="product_review_create"),
    path('reviews/<int:pk>/update/', UpdateReview.as_view(), name="update_review"),
    path('reviews/<int:pk>/delete/', DeleteReview.as_view(), name="delete_review"),
]

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
# from django.urls import reverse

# Create your models here.


CATEGORY_CHOICES = [('Confectionery', 'Кондитерка'), ('Grocery', 'Бакалея'), ('Drinks', 'Напитки')]
GRADE_CHOICES = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]


class BaseModel(models.Model):
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_time = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")

    class Meta:
        abstract = True


class Product(BaseModel):
    product_name = models.CharField(max_length=35, null=False, blank=False, verbose_name="Название продукта")
    category = models.CharField(max_length=20, null=False, blank=False, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                                verbose_name="Категория продукта")
    product_description = models.TextField(max_length=3000, verbose_name="Описание продукта")
    product_img = models.ImageField(upload_to="product_img", null=True, blank=True, verbose_name="Фото продукта")

    def __str__(self):
        return f"{self.id}. {self.product_name}."

    # def get_absolute_url(self):
    #     return reverse("webapp:ProductView", kwargs={"pk": self.pk})

    class Meta:
        db_table = "products"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"


class Review(BaseModel):
    author = models.ForeignKey(get_user_model(), related_name="reviews", verbose_name="Автор", default=1,
                               on_delete=models.SET_DEFAULT)
    product = models.ForeignKey("webapp.Product", on_delete=models.CASCADE, related_name="products",
                                verbose_name="Продукт")
    feedback_text = models.TextField(max_length=3000, null=False, blank=False, verbose_name="Текст отзыва к продукту")
    grade = models.CharField(max_length=20, null=False, blank=False, choices=GRADE_CHOICES, default=GRADE_CHOICES[0][0],
                             verbose_name="Оценка продукта")
    feedback_moderated = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.id}. {self.author}"

    class Meta:
        db_table = "review"
        verbose_name = "отзыв"
        verbose_name_plural = "Список отзывов"

webapp/forms.py
from django import forms
from webapp.models import Product, Review


class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Найти')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []


# class OrderForm(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = ["name", "phone", "address"]

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["feedback_text"]

webapp/views.py
from django.shortcuts import render

# Create your views here.

webapp/views/base_view.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import ListView

from webapp.forms import SearchForm


class SearchView(ListView):
    search_form_class = SearchForm
    search_form_field = "search"
    query_name = "query"
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.search_value:
            return self.model.objects.filter(self.get_query())
        return self.model.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({self.search_form_field: self.search_value})
            context[self.query_name] = query
            context[self.search_form_field] = self.search_value
        return context

    def get_search_form(self):
        return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get(self.search_form_field)

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value}
            query = query | Q(**kwargs)
        return query

webapp/views/products.py
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, DeleteView, DetailView, CreateView

from webapp.forms import ProductForm
from webapp.models import Product
from webapp.views.base_view import SearchView


class IndexView(SearchView):
    model = Product
    template_name = 'product/index.html'
    ordering = ['category', 'product_name']
    search_fields = ['product_name__icontains']
    paginate_by = 6
    context_object_name = 'products'

    # def get_queryset(self):
    #     return super().get_queryset().filter(category__gt=0)


class ProductView(DetailView):
    model = Product
    template_name = 'product/product_view.html'
    # queryset = Product.objects.filter(products__gt=0)
    context_object_name = 'products'




class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_create.html'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_update.html'


    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'product/product_delete.html'
    success_url = reverse_lazy('webapp:index')

webapp/views/reviews.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import ReviewForm
from webapp.models import Product, Review


class CreateReviewView(CreateView):
    form_class = ReviewForm
    template_name = "reviews/create.html"

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get("pk"))
        user = self.request.user
        form.instance.product = product
        form.instance.author = user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class UpdateReview(UserPassesTestMixin, UpdateView):
    form_class = ReviewForm
    template_name = "reviews/update.html"
    model = Review

    def test_func(self):
        return self.get_object().author == self.request.user or\
               self.request.user.has_perm('webapp.change_review')

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class DeleteReview(DeleteView):
    model = Review

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})

webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Магазин{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href={% url 'webapp:index' %}>Домой</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% block nav %}{% endblock %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webapp:product_create' %}">Создание товара</a>
                </li>
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'webapp:cart' %}">Корзина</a>#}
{#                </li>#}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:logout" %}">Выйти</a>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link">Здравствуйте <a
                                href="{% url "accounts:profile" request.user.pk %}">{{ user.username }}</a></p>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:login" %}?next={{ request.get_full_path }}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:registration" %}?next={{ request.get_full_path }}">Зарегистрироваться</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>