exam8/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import IndexView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView

# from webapp.views import IndexView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView, CartAddView, \
#     CartView, CartDeleteView, CartDeleteOneView, OrderCreate
from webapp.views.reviews import CreateReviewView, UpdateReview, DeleteReview

app_name = "webapp"

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('products/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    # path('product/<int:pk>/add-to-cart/', CartAddView.as_view(), name='add_to_cart'),
    # path('cart/', CartView.as_view(), name='cart'),
    # path('cart/<int:pk>/delete/', CartDeleteView.as_view(), name='remove_for_cart'),
    # path('cart/<int:pk>/one-delete/', CartDeleteOneView.as_view(), name='remove_one_for_cart'),
    # path('order/create/', OrderCreate.as_view(), name='order_create')
    path('product/<int:pk>/review/add/', CreateReviewView.as_view(), name="product_review_create"),
    path('reviews/<int:pk>/update/', UpdateReview.as_view(), name="update_review"),
    path('reviews/<int:pk>/delete/', DeleteReview.as_view(), name="delete_review"),
]

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
# from django.urls import reverse

# Create your models here.


CATEGORY_CHOICES = [('Confectionery', 'Кондитерка'), ('Grocery', 'Бакалея'), ('Drinks', 'Напитки')]
GRADE_CHOICES = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]


class BaseModel(models.Model):
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_time = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")

    class Meta:
        abstract = True


class Product(BaseModel):
    product_name = models.CharField(max_length=35, null=False, blank=False, verbose_name="Название продукта")
    category = models.CharField(max_length=20, null=False, blank=False, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                                verbose_name="Категория продукта")
    product_description = models.TextField(max_length=3000, verbose_name="Описание продукта")
    product_img = models.ImageField(upload_to="product_img", null=True, blank=True, verbose_name="Фото продукта")

    def __str__(self):
        return f"{self.id}. {self.product_name}."

    # def get_absolute_url(self):
    #     return reverse("webapp:ProductView", kwargs={"pk": self.pk})

    class Meta:
        db_table = "products"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"


class Review(BaseModel):
    author = models.ForeignKey(get_user_model(), related_name="reviews", verbose_name="Автор", default=1,
                               on_delete=models.SET_DEFAULT)
    product = models.ForeignKey("webapp.Product", on_delete=models.CASCADE, related_name="products",
                                verbose_name="Продукт")
    feedback_text = models.TextField(max_length=3000, null=False, blank=False, verbose_name="Текст отзыва к продукту")
    grade = models.CharField(max_length=20, null=False, blank=False, choices=GRADE_CHOICES, default=GRADE_CHOICES[0][0],
                             verbose_name="Оценка продукта")
    feedback_moderated = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.id}. {self.author}"

    class Meta:
        db_table = "review"
        verbose_name = "отзыв"
        verbose_name_plural = "Список отзывов"

webapp/forms.py
from django import forms
from webapp.models import Product, Review


class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Найти')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []


# class OrderForm(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = ["name", "phone", "address"]

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["feedback_text"]

webapp/views.py
from django.shortcuts import render

# Create your views here.

webapp/views/base_view.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import ListView

from webapp.forms import SearchForm


class SearchView(ListView):
    search_form_class = SearchForm
    search_form_field = "search"
    query_name = "query"
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.search_value:
            return self.model.objects.filter(self.get_query())
        return self.model.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({self.search_form_field: self.search_value})
            context[self.query_name] = query
            context[self.search_form_field] = self.search_value
        return context

    def get_search_form(self):
        return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get(self.search_form_field)

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value}
            query = query | Q(**kwargs)
        return query

webapp/views/products.py
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, DeleteView, DetailView, CreateView

from webapp.forms import ProductForm
from webapp.models import Product
from webapp.views.base_view import SearchView


class IndexView(SearchView):
    model = Product
    template_name = 'product/index.html'
    ordering = ['category', 'product_name']
    search_fields = ['product_name__icontains']
    paginate_by = 6
    context_object_name = 'products'

    # def get_queryset(self):
    #     return super().get_queryset().filter(category__gt=0)


class ProductView(DetailView):
    model = Product
    template_name = 'product/product_view.html'
    # queryset = Product.objects.filter(products__gt=0)
    context_object_name = 'products'




class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_create.html'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_update.html'


    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'product/product_delete.html'
    success_url = reverse_lazy('webapp:index')

webapp/views/reviews.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import ReviewForm
from webapp.models import Product, Review


class CreateReviewView(CreateView):
    form_class = ReviewForm
    template_name = "reviews/create.html"

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get("pk"))
        user = self.request.user
        form.instance.product = product
        form.instance.author = user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class UpdateReview(UserPassesTestMixin, UpdateView):
    form_class = ReviewForm
    template_name = "reviews/update.html"
    model = Review

    def test_func(self):
        return self.get_object().author == self.request.user or\
               self.request.user.has_perm('webapp.change_review')

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class DeleteReview(DeleteView):
    model = Review

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})

webapp/templates/product/index.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="text-center">Товары</h1>
    <div class="my-3">{% include 'partial/search.html' %}</div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    <div class="row my-3">
        {% for product in products %}
            <div class="col-12 col-md-4 col-lg-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title"><a
                                href="{% url "webapp:product_view" product.pk %}">{{ product.product_name }}</a></h5>
                        <p class="card-text">Категория: {{ product.get_category_display }}</p>


                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'webapp:product_update' product.pk %}">Изменить</a>
                            <a class="btn btn-danger" href="{% url 'webapp:product_delete' product.pk %}">Удалить</a>

                        </div>


                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

webapp/templates/product/product_create.html
{% extends 'base.html' %}

{% block title %}Создание{% endblock %}

{% block content %}
    <h1>Создать товар</h1>
    <form method='POST' action='{{ action_url }}' enctype='multipart/form-data'>
        {% include 'partial/form.html' with button_text="Создать" %}
    </form>

{% endblock %}

webapp/templates/product/product_delete.html
{% extends 'base.html' %}

{% block title %}Удаление{% endblock %}

{% block nav %}
    <li class="nav-item"><a class="nav-link" href="{% url 'webapp:product_view' product.pk %}">Отмена</a></li>
{% endblock %}

{% block content %}
    <h1>Вы уверены, что хотите удалить товар "{{ product.product_name }}" ({{ product.get_category_display }})?</h1>
    <form action="{% url "webapp:product_delete" product.pk %}" method="post">
        {% csrf_token %}
        <div class="btn-group">
            <button class="btn btn-danger" type="submit">Да</button>
            <a class="btn btn-primary" href="{% url 'webapp:product_view' product.pk %}">Отмена</a>
        </div>
    </form>
{% endblock %}

webapp/templates/product/product_update.html
{% extends 'base.html' %}

{% block title %}Изменение{% endblock %}

{% block content %}
    <h1>Изменить товар</h1>

    <form method='POST' action='{{ action_url }}' enctype='multipart/form-data'>
        {% include 'partial/form.html' with button_text="Изменить" %}
    </form>
{% endblock %}

webapp/templates/product/product_view.html
{% extends 'base.html' %}

{% block title %}Просмотр{% endblock %}

{% block nav %}
    <li class="nav-item"><a class="nav-link" href="{% url 'webapp:product_update' products.pk %}">Изменить</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'webapp:product_delete' products.pk %}">Удалить</a></li>
{% endblock %}

{% block content %}
    {% if products.product_img %}
        <img src="{{ products.product_img.url }}" class="card-img-top w-25" alt="...">
    {% endif %}

    <div class="card">
        <div class="card-body">
            <h2>{{ products.product_name }}</h2>
            <p class="card-text">Категория: {{ products.get_category_display }}</p>
            <p class="pre">Описание: {{ products.product_description }}</p>
        </div>
    </div>

    <li class="nav-item">
        <a class="nav-link" href="{% url "webapp:product_review_create" products.pk %}">Добавить коммент</a>
    </li>

    <h3 class="my-3 text-center">Комментарии</h3>
    <div class="row">
        {% for review in products.review %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <p class="card-text">{{ review.feedback_text }}</p>
                    </div>
                    <div class="btn-group w-100" role="group" aria-label="Basic mixed styles example">
                        <a class="btn btn-danger" href="{% url "webapp:update_review" review.pk %}">Изменить</a>
                        <a class="btn btn-warning" href="{% url "webapp:delete_review" review.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Комментариев нет</p>
        {% endfor %}
    </div>

{% endblock %}